### ISSUE TITLE
Hovering over unlocked storage mode responses shows the wrong state

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4621] opened 2022-08-22 09:20 UTC
<img width="452" alt="image" src="https://user-images.githubusercontent.com/103998698/185886644-bf67a87d-ccd7-4210-b76b-7169601f36d0.png">

**Comment by mantariksh** [comment] 2022-08-22 11:15
duplicate of #4128

**Closed as completed by mantariksh** 2022-08-22 11:15 UTC
Labels: react
