### ISSUE TITLE
Add placeholder for empty checkbox and radio options textinput when editing field

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4638] opened 2022-08-22 09:26 UTC
Radio button editor options have no placeholder if I type and delete it.
<img width="520" alt="image35" src="https://user-images.githubusercontent.com/22133008/185887872-e471076f-6ea9-4218-8363-efbb16b4ffd9.png">

**Comment by mantariksh** [comment] 2022-08-22 11:31
Duplicate of #4625

**Closed as not planned by mantariksh** 2022-08-22 11:31 UTC
