### ISSUE TITLE
[8] Update SES configuration

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#3754] opened 2022-04-13 17:20 UTC
Issue description [here](https://docs.google.com/document/d/1ccgdAHuyiJqyE_Ivrw_89bmowSIFrkx7wFHSoIAcvIg/edit#heading=h.vgpb9qfli6b8)

**Comment by amitogp** [comment] 2022-11-01 07:47
This issue has compliance and performance impact. Can also potentially solve email OTP issue.
This may also require purchasing new IPs and get them warmed up.

**Comment by wanlingt** [comment] 2022-11-02 03:17
duplicate of https://github.com/opengovsg/formsg-private/issues/91

**Closed by wanlingt** 2022-11-02 03:17 UTC
Labels: P2
