### ISSUE TITLE
Create form modal design updates to reflect hierarchy

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4332] opened 2022-07-26 04:34 UTC
Show that download is the most important; checkbox to appear after download

**Comment by pearlyong** [comment] 2022-08-03 03:09
discussed and updated [here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=11024%3A142496)

**Comment by karrui** [comment] 2022-08-11 10:39
duplicate of #4291

**Closed as not planned by karrui** 2022-08-11 10:39 UTC
Labels: design
