### ISSUE TITLE
client: Migrate admin-console.client.service to pure TypeScript function

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#1445] opened 2021-03-24 07:46 UTC
This issue tracks the migration of AdminConsole in `src/public/modules/users/services/admin-console.client.service.js` to its TypeScript counterpart that does not rely on AngularJS.

Related to #1339

**Comment by liangyuanruo** [comment] 2021-03-30 10:32
Duplicate of #1521

**Closed by liangyuanruo** 2021-03-30 10:32 UTC
