### ISSUE TITLE
Icon to search for submission ID is not clickable

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#3111] opened 2021-11-29 10:56 UTC
When attempting to search for submission ID in storage mode under data tab, clicking on the search icon does not trigger the search box to appear. Instead I have to hover my mouse around the top right of the icon until I see the cursor change to a pointer, upon which I can click and trigger the search box.

**Comment by LinHuiqing** [comment] 2023-09-15 10:35
Closing as I am unable to reproduce and I don't see any complaints for this on support tix!

**Closed by LinHuiqing** 2023-09-15 10:35 UTC
