### ISSUE TITLE
Paragraph field editor still says 'statement'. Need to uodate the copy.

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#4755] opened 2022-08-29 10:20 UTC
<img width="415" alt="image" src="https://user-images.githubusercontent.com/107169604/187180664-9d5836ee-04b0-4e72-928f-c8dc5a2668e4.png">

**Comment by mantariksh** [comment] 2022-08-31 03:10
duplicate of #4751

**Closed as completed by mantariksh** 2022-08-31 03:10 UTC
