### ISSUE TITLE
Ensure static and unique URL for payment page to support refresh and resume

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5969] opened 2023-03-22 00:35 UTC
If the payment is pending: Open payment element
If it's already successful: Show payment success / thank you page

It's ok if they see feedback page again because of redirection to thankyou page.

**Comment by justynoh** [comment] 2023-03-22 02:59
Duplicate of #5932

**Closed as not planned by justynoh** 2023-03-22 02:59 UTC
Labels: payment
