### ISSUE TITLE
Submission: Infinite loading on submission

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#5497] opened 2022-11-30 03:11 UTC
We are not sure what is the cause for this but it is potentially an issue with Recaptcha.

These are some tickets for respondents that encountered this issue (non-exhaustive):

https://formsg.zendesk.com/agent/tickets/13619
https://formsg.zendesk.com/agent/tickets/15391
https://formsg.zendesk.com/agent/tickets/15687
https://formsg.zendesk.com/agent/tickets/15624
https://formsg.zendesk.com/agent/tickets/15601
https://formsg.zendesk.com/agent/tickets/15702
https://formsg.zendesk.com/agent/tickets/14546
https://formsg.zendesk.com/agent/tickets/14496
https://formsg.zendesk.com/agent/tickets/14458
https://formsg.zendesk.com/agent/tickets/14458
https://formsg.zendesk.com/agent/tickets/12999
https://formsg.zendesk.com/agent/tickets/12983
https://formsg.zendesk.com/agent/tickets/15397

Updates: If a respondent clicks outside of the recaptcha box, we do not allow submission again.

**Comment by darrelhong** [comment] 2022-12-03 06:35
likely caused by getCaptchaResponse promise not resolving upon clicking outside of captcha https://github.com/opengovsg/FormSG/blob/47b01b3a0a16c3a37523373623d92008877ea069/frontend/src/features/public-form/PublicFormProvider.tsx#L197

https://user-images.githubusercontent.com/39296145/205428952-8db09d82-9e1b-47f4-8400-63de4fe60733.mov

**Closed as completed** 2022-12-07 01:26 UTC
Labels: eng
