### ISSUE TITLE
Proceed to pay captcha screen is not scrollable

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6047] opened 2023-04-05 01:17 UTC
bug link: https://opengovproducts.slack.com/files/U03BTM1GMNF/F050Y8NLZKK/trimmed_captcha_video_problem.mp4

Marked as P4 because users still have the workaround of zooming out.

**Comment by foochifa** [comment] 2023-04-05 03:08
Duplicate of #6002!

**Closed as not planned by foochifa** 2023-04-05 03:08 UTC
Labels: payment
