### ISSUE TITLE
Country field with countries pre-populated in dropdown list

### ISSUE THREAD

**Issue by staceytan1998** [opengovsg/FormSG#6223] opened 2023-05-01 13:46 UTC
**What**
A dropdown field containing every country.

**Why**
- Countries are standardised and will not change regularly. Don't need admins to create a dropdown for it.
- Improves accuracy of data collected

**Comment by jia1** [comment] 2023-07-02 06:13
Is this a duplicate of #481? I am working to get the relevant PR merged.

**Closed as completed** 2023-08-02 01:57 UTC
Labels: contribute
