### ISSUE TITLE
Refactor submissions

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#2750] opened 2021-09-06 06:57 UTC
Link to issue description

https://docs.google.com/document/d/1ccgdAHuyiJqyE_Ivrw_89bmowSIFrkx7wFHSoIAcvIg/edit#heading=h.oy3p4whm9unj

**Comment by mantariksh** [comment] 2022-07-27 10:49
duplicate of #3394

**Closed by mantariksh** 2022-07-27 10:49 UTC
Labels: P3, save ops time
