### ISSUE TITLE
Change form status copy on Workspace page

### ISSUE THREAD

**Issue by pearlyong** [opengovsg/FormSG#4635] opened 2022-08-22 09:25 UTC
Can call it Open or Closed since we’re using that for Settings

<img width="88" alt="Screenshot 2022-08-22 at 5 24 31 PM" src="https://user-images.githubusercontent.com/28617936/185887571-7bdc9e8a-22b7-4d1a-9456-7f75b753afb1.png">

**Comment by mantariksh** [comment] 2022-08-22 09:31
duplicate of #4636

**Closed as completed by mantariksh** 2022-08-22 09:31 UTC
Labels: react
