### ISSUE TITLE
Better error identification of form submission errors

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#2518] opened 2021-08-03 04:03 UTC
During the last release of 5.22, we were monitoring submission failures in Google Analytics.

The number did not spike, so we did not suspect the build was broken, but we did see some occasional submission failures, and decided to investigate just in case. 

It is not straightforward at all to identify the cause a submission failure. We resorted to making a copy of the form, and doing a manual submission, just to verify the form structure, fields, logic, and validation were OK, but this is time consuming. 

TODO: find a way to identify error cause (error codes? stack traces? messages?) faster. Sentry could be a candidate for this.

**Comment by syan-syan** [comment] 2021-08-05 06:29
duplicate of #2515

**Closed by syan-syan** 2021-08-05 06:29 UTC
